####This is the code to reproduce network-analysis findings from the PEACE study. This documented was created with amended materials provided by the FSL team in Oxford (https://open.win.ox.ac.uk/pages/fslcourse/practicals/fslnets/index.html). For any questions,
####please ask the author (michael.colwell@psych.ox.ac.uk).

####Recommended use: execute this python script within an 'fslnets' singularity container.

####Initial load-in and spectra generation.

#By default this code runs the 'weighted' analysis, please change the directory on line 16 to '/timeseries_extraction/Nonweighted_Combined_Nodes/True_Filtered/'.

import os
from fsl import nets
import matplotlib.pyplot as plt  # Import matplotlib for plotting
import numpy as np

# Define the parent directory where your node folders are stored
nodes_dir = './timeseries_extraction/Weighted_Combined_Nodes/True_Filtered/' #Change folder to 'Combined_Nodes' for non-weighted analysis.
vis_dir = './visualisation/'

# Now use nets.load with the combined folder
ts = nets.load(nodes_dir,
               1.4,
               varnorm=0,
               thumbnaildir=vis_dir)

# Plot the spectra
nets.plot_spectra(ts)

# Define the path where the plot will be saved
plot_filename = './spectra/spectra_plot.png'

# Save the plot to the specified file with high quality
plt.savefig(plot_filename, dpi=300, bbox_inches='tight')
print(f"Plot saved to {plot_filename}")

####Cleaning

goodnodes = [0, 1, 2, 3, 4]

nets.clean(ts, goodnodes, True)

#####Set-up the network structure

Fnetmats = nets.netmats(ts, 'corr',   True)
Pnetmats = nets.netmats(ts, 'ridgep', True, 0.1)

Fnetmats.shape
print("Network shape:")
print(Fnetmats.shape)

######Perform group-level network analysis

Znet_F, Mnet_F = nets.groupmean(ts, Fnetmats, False)
Znet_P, Mnet_P = nets.groupmean(ts, Pnetmats, True, 'Partial correlation')

nets.plot_hierarchy(ts, Znet_F, Znet_P, 'Full correlations', 'Partial correlations')

plt.savefig('./matrices/hierarchy_plot.png', dpi=300, bbox_inches='tight')

# Assuming ts, Pnetmats are already defined and valid
Znet_P, Mnet_P = nets.groupmean(ts, Pnetmats, True, 'Partial correlation')

# After the plot is automatically generated by groupmean, capture the current figure
fig = plt.gcf()

fig.savefig("./plot.pdf", format="pdf", bbox_inches="tight")

# Optionally, clear the figure to avoid overlap with any future plots
plt.clf()


####################

#Node 0 = Hippocampus
#Node 1 = Mammilary Zone
#Node 2 = Basal forebrain
#Node 3 = Entorhinal cortex
#Node 4 = Perirhinal cortex

# Example timeseries data and predefined adjacency matrix for 5 nodes (replace with actual data)
# Assume ts is your timeseries data for all subjects
Znet_F, Mnet_F = nets.groupmean(ts, Fnetmats, False)

# Define an adjacency matrix based on domain knowledge (predefined)
# Example for 5 nodes, where 1 means there is a connection, and 0 means no connection
#adj_matrix = np.array([[0, 1, 1, 1, 1],  # Node 1 connected to Node 2
#                       [1, 0, 1, 0, 0],  # Node 2 connected to Node 1 and Node 3
#                       [1, 0, 0, 0, 0],  # Node 3 connected to Node 2 and Node 4
#                       [1, 0, 0, 0, 1],  # Node 4 connected to Node 3 and Node 5
#                       [1, 0, 0, 1, 0]]) # Node 5 connected to Node 4
                       
adj_matrix = np.array([[1, 1, 1, 1, 1],  # Node 1 connected to Node 2
                       [1, 1, 1, 1, 1],  # Node 2 connected to Node 1 and Node 3
                       [1, 1, 1, 1, 1],  # Node 3 connected to Node 2 and Node 4
                       [1, 1, 1, 1, 1],  # Node 4 connected to Node 3 and Node 5
                       [1, 1, 1, 1, 1]]) # Node 5 connected to Node 4                   

# Apply the adjacency matrix as a mask on your correlation matrix
# Here we only keep correlations between connected nodes (based on adjacency matrix)
Mnet_F = Mnet_F * adj_matrix  # Element-wise multiplication to zero out unwanted edges

# Apply thresholding if needed (e.g., keep correlations above 0.5)
threshold = 0.5
Mnet_F[Mnet_F < threshold] = 0  # Zero out weak connections

# Plot the connectivity matrix using Matplotlib
plt.figure(figsize=(8, 6))
plt.imshow(Mnet_F, cmap='hot', interpolation='none')  # Use a color map for visualization
plt.colorbar(label='Connectivity Strength')  # Color bar to represent the strength of the connections
plt.title("Network Connectivity with Defined Edges")
plt.xlabel("Nodes")
plt.ylabel("Nodes")
plt.tight_layout()

# Save the plot to a file
plt.savefig('network_connectivity.png', dpi=300, bbox_inches='tight')

#####Between-group analaysis

p_corr,p_uncorr = nets.glm(ts, Pnetmats, './Analysis_Designs/design.mat', './Analysis_Designs/design.con');

nets.boxplots(ts, Pnetmats, Znet_P, p_corr[0], groups=(6, 6))

#Multivate ML analysis

import io
import sys

# Capture the output
output = io.StringIO()
sys.stdout = output

# Run the classify function (which prints the verbose output)
nets.classify(Pnetmats, (6, 6))

# Reset stdout back to normal
sys.stdout = sys.__stdout__

# Print the captured output
print(output.getvalue())

#####End of code#####